language: node_js
node_js:
- '7'
notifications:
  slack:
    secure: SuTmNwBRy9DdV83G0TtMV5pT2NcpPPFgH7JdD6Oowj5h5ChlUBRn7om8aqeZ61TGl4t56w0qoNgCeelwZu6M7xN5LcyvnaZBIcfbx5C4/zOLGCISOWF0gCN09Y3tgHs2Aii1vp1CG2EOkVb8rLfDqIaDLJxOGfZ9YQlv87iLISUB/SxBEDBWPZj0lYViaz8KTqv7Y0OHSy0TL0Zop5pDOSkZGEJmv4OvWCgYONiway0uUMz1fvW61JbxkwFfjHuKs1t8uhsZmw7lp9wuARmULCJbMRsEar1Qgci/8V5lgMFeiJdKJiTIzT5OEcdmvZhvIJLM0WbbqUShwbw/xJHvlYesihBkAiTE5M/C8WT7LA3LCPn/wMiUqpiF+0NxElynqV4VFlx1m0acU1csIZcMEoCQdg8gTC+x4RNslZYvkzaRNZFSRyBd/IEOJwmRp0ohGUViRA9WD+RrPvoK8OCDbbeSEwNvYYaF/aE4BIDnVfxEiaUHre8r4nTbSDwaY2eSUpodVmoblAk7pTUG52tN/v9NaAa2SIP+vmLeDIW54QeUTTxS5MoI3cYOOT678q/+NFqn/n1X997nycfHZNBD/vZ3tClmgUZr0/wNduU8qK6paUCtlKuyZcukJU/4co4SkZg8p6627rZIk4Q+KpgJZKVRpvehdPGv+oPDCCQcJt4=
